id: I745A47E3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T20:14:07+00:00'
last_modified: '2022-06-07T17:08:49.689148+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23681
  title: སྒྲུབ་ཐབས་ཀུན་བཏུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8DA9:
      image_group_id: I2416
      title: ''
      total_pages: 686
      order: 1
      base_file: 8DA9.txt
    '3919':
      image_group_id: I2417
      title: ''
      total_pages: 696
      order: 2
      base_file: 3919.txt
    E54E:
      image_group_id: I2418
      title: ''
      total_pages: 676
      order: 3
      base_file: E54E.txt
    49C2:
      image_group_id: I2419
      title: ''
      total_pages: 724
      order: 4
      base_file: 49C2.txt
    633C:
      image_group_id: I2420
      title: ''
      total_pages: 742
      order: 5
      base_file: 633C.txt
    793D:
      image_group_id: I2421
      title: ''
      total_pages: 698
      order: 6
      base_file: 793D.txt
    8D89:
      image_group_id: I2422
      title: ''
      total_pages: 772
      order: 7
      base_file: 8D89.txt
    '4931':
      image_group_id: I2423
      title: ''
      total_pages: 744
      order: 8
      base_file: 4931.txt
    B060:
      image_group_id: I2424
      title: ''
      total_pages: 730
      order: 9
      base_file: B060.txt
    0DF3:
      image_group_id: I2425
      title: ''
      total_pages: 728
      order: 10
      base_file: 0DF3.txt
    '2882':
      image_group_id: I2426
      title: ''
      total_pages: 702
      order: 11
      base_file: 2882.txt
    AA30:
      image_group_id: I2427
      title: ''
      total_pages: 876
      order: 12
      base_file: AA30.txt
    F32B:
      image_group_id: I2428
      title: ''
      total_pages: 894
      order: 13
      base_file: F32B.txt
    '2314':
      image_group_id: I2475
      title: ''
      total_pages: 676
      order: 14
      base_file: 2314.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
